name: Simple UDF CI

on: [push, pull_request]

env:
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  WAREHOUSE_HTTP_PATH: ${{ secrets.WAREHOUSE_HTTP_PATH }}
  CATALOG_NAME: ${{ secrets.CATALOG_NAME }}
  SCHEMA_NAME: ${{ secrets.SCHEMA_NAME }}

jobs:
  test-and-register:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Install test dependencies
      run: pip install -r temporals/test/requirements.txt

    - name: Run test suite
      run: |
        echo "Running test harness..."
        pytest temporals/test/ --maxfail=1 --disable-warnings --tb=short

    - name: Install Databricks CLI
      uses: databricks/setup-cli@main

    - name: Verify connectivity
      run: databricks workspace list /

    - name: Where am I
      run: pwd

    - name: Run SQL
      run: dbsqlcli --clirc temporals/core/.dbsqlclirc -e temporals/core/register_udfs.sql
        --hostname $DATABRICKS_HOST \
        --http-path $WAREHOUSE_HTTP_PATH \
        --access-token $DATABRICKS_TOKEN
